# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

# Setup
title:               Daily Flip
tagline:             'Das Eintracht Tagebuch seit 1999.'
description:         'Mein persönliches Fan-Tagebuch seit 1999.'
url:                 https://eintracht-stats.de
baseurl:             ''
paginate:            10

# About/contact
author:
  name:              Philipp Breither
  url:               https://eintracht-stats.de/impressum
  email:             flip@eintracht-stats.de

# Custom vars
version:             1.0.0
